
spring:
    profiles:
        include:
          # Do not include `default`, as by `default` we include `fake_player` 
        - default_server
        - default_player
        group:
            # `default` is used for quick-start: we enable fake security
            default:
            - fake_server
            - fake_player
            default_server:
            - inject_default_games