
spring:
    profiles:
        group:
            # `default` is used for quick-start
            default:
            - monolith
            - unsafe
            unsafe:
            - monolith
            default_server:
            - monolith
            - inject_default_games

