
spring:
    profiles:
      group:
        default:
        # Renamed to enable merging in monolith
        - "default_player"
        - "default_server"
        - "server"
        - "fake_player"
        - inject_default_games