spring:
    application.name: kumite-player
    # https://stackoverflow.com/questions/26105061/spring-boot-without-the-web-server
    main.web-application-type: NONE
    profiles:
        #include:
        #  # Do not include `default`, as by `default` we include `fake_player` 
        #- default_server
        group:
            # `default` is used for quick-start: we enable fake security
            default:
            - unsafe
            unsafe:
            - fakeuser
            - unsafe_player
            - unsafe_server
            - unsafe_oauth2

logging:
    level:
        org.springframework.security: INFO
        eu.solven.kumite.app.webflux.KumiteExceptionRoutingWebFilter: DEBUG

# kumite.playerId: "NEEDS_A_PROPER_VALUE"

kumite.server:
    # One need to generate a refresh tken from the `js` app, on route `/html/me`
    refresh_token: "NEEDS_A_PROPER_VALUE"


