# unsafe_external_oauth2: activates development version of oauth2 providers: useful to check the User-login flow


kumite.login:
    # https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html
    # redirectUri: `{baseUrl}/login/oauth2/code/{registrationId}`
    oauth2:
        github:
            # https://github.com/settings/applications/2686735
            clientId: Ov23liakPa9YkyfEZGZE
            clientSecret: 35faf73b496bb30fa17c1dd2f9fc8111874965ca
        google:
            # https://developers.google.com/identity/sign-in/web/sign-in?hl=fr
            # https://console.cloud.google.com/apis/credentials?hl=fr&project=kumite
            clientId: 635294738113-sftufj1etk97bqdhj7m6949behc3clhn.apps.googleusercontent.com
            clientSecret: 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
