spring:
    profiles:
        # Do not add any default `include`, else `default would never kicks in`
        group:
            # `default` is used for quick-start: we enable fake security
            default:
                - default_server
                - fake
            secured:
                - default_server
            heroku:
                - secured
            unsafe_external_oauth2:
                - default_server
            fake:
            - default_server
            # unsafe_server provides unsafe security (JWT signature, etc)
            - unsafe_server
            # fake_user introduces a default fakeAccount with a default fakePlayer
            - fake_user
            unsafe_server:
                - default_server
            default_server:
            - inject_default_games

logging:
    level:
        org.springframework.security: INFO
        eu.solven.kumite.app.webflux.KumiteExceptionRoutingWebFilter: DEBUG

kumite.login:
   # Used to sign the JWT, which are used to interact withthe API
   signing-key: 'NEEDS_TO_BE_DEFINED'
