spring:
  profiles:
    include: 
      - server
      - default
    group:
      default:
      # - server
      - default_server
      - fake_player
      - inject_default_games

logging:
  level:
    org.springframework.security: INFO
    eu.solven.kumite.app.webflux.KumiteExceptionRoutingWebFilter: DEBUG

kumite.login:
  signing-key: 'NEEDS_TO_BE_DEFINED'
