spring:
  application.name: kumite-server
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${kumite.login.oauth2.github.clientId}
            clientSecret: ${kumite.login.oauth2.github.clientSecret}
          google:
            client-id: google-client-id
            client-secret: google-client-secret
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    org.springframework.security: INFO

kumite.login:
  signing-key: 'NEEDS_TO_BE_DEFINED'