name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Package the server to serve API and JS
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Install Kumite Server
      # `install` so that each module is available in local repository, as later mvn command will not be executed on the root
      run: mvn install -DskipTests -pl :server -am
    - name: Check Running ContestsServer
      run: (cd ./server; mvn spring-boot:run;)
    - name: Check Running ContestsServer from JS
      working-directory: ./js
      run: (cd ./server; mvn spring-boot:run;)
        
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install NPM dependencies
      working-directory: ./js
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./js
      run: npx playwright install --with-deps
    #- name: Run Playwright tests
    #  working-directory: ./js
    #  run: npm run pw_localhost8080
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
